-- ══════════════════════════════════════════════════════════════════════
-- الجداول الأساسية الأربعة — البنية الفعلية
-- ══════════════════════════════════════════════════════════════════════
--
-- هذه الجداول أُنشئت يدوياً في لوحة Supabase قبل أن يبدأ حفظ الترحيلات،
-- فلم يكن لها ملف. هذا الملف يحفظ بنيتها كما هي في قاعدة الإنتاج فعلاً.
--
-- ✅ استُخرجت من القاعدة نفسها عبر supabase/introspect.sql — لا تقدير فيها.
--    الأعمدة وأنواعها وقيمها الافتراضية والمفاتيح والفهارس والصلاحيات.
--
-- الملف آمن للتشغيل على قاعدة قائمة: كل شيء `if not exists`، فلا يُتلف
-- بيانات ولا يُسقط جدولاً.
--
-- ⚠️ ثلاث ملاحظات على البنية الحقيقية موثّقة في محلّها أدناه:
--    ① المفتاح الأساسي لـ book_sources يمنع تعدّد الكتب (عطل فعلي)
--    ② ثلاثة فهارس متطابقة على curriculum
--    ③ سياسات مكرّرة، وواحدة تكشف قائمة البُرد
-- ══════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────
-- ١) curriculum — المنهج: وحدات ودروس كل مادة  (٢٨٩٣ صفاً)
-- ─────────────────────────────────────────────────────────────
-- منه يُشتقّ رقم الدرس الموحّد (stableLessonId) الذي يربط المعلمات ببعضهن:
--   hash(semester | subject | grade | unit | lesson)
-- فتعديل نصّ هذه الأعمدة يُغيّر الرقم ويقطع الربط بالمخزن المشترك.
--
-- ملحوظة: grade وpage عددان (integer) لا نصّان. الكود يمرّر String(grade)
-- وPostgREST يحوّله، فيعمل — لكن انتبه لذلك عند أي استعلام مباشر.

create table if not exists public.curriculum (
  id        bigint generated by default as identity primary key,
  semester  text not null,
  grade     integer not null,          -- عدد لا نصّ
  subject   text not null,
  unit      text not null,
  lesson    text not null,
  sort      integer default 0,
  page      integer,                   -- عدد لا نصّ
  book_no   integer not null default 1
);

-- ② ثلاثة فهارس متطابقة تماماً على (semester, subject, grade, sort):
--      idx_curriculum_lookup · idx_curriculum_path · curriculum_lookup
--    واحد يكفي. الزائدان يُبطئان كل كتابة ويشغلان مساحة بلا فائدة.
--    التنظيف في supabase/cleanup_duplicates.sql
create index if not exists idx_curriculum_lookup
  on public.curriculum (semester, subject, grade, sort);

alter table public.curriculum enable row level security;

drop policy if exists curr_read on public.curriculum;
create policy curr_read on public.curriculum
  for select to authenticated using (true);

drop policy if exists curr_admin_write on public.curriculum;
create policy curr_admin_write on public.curriculum
  for all to authenticated using (is_app_admin()) with check (is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٢) book_sources — أين تُخزَّن صور صفحات كل كتاب  (١٣ صفاً)
-- ─────────────────────────────────────────────────────────────
-- offset_pages: الفرق بين رقم الصفحة المطبوع ورقم ملف الصورة.
--
-- ① ⚠️ عطل فعلي: المفتاح الأساسي (grade, subject, semester) يمنع وجود أكثر
--    من كتاب واحد لكل مادة في الفصل الواحد — وهو بالضبط ما تحتاجه الحلقة
--    الأولى (ثلاثة كتب للمادة الواحدة).
--
--    ترحيل 20260714 أضاف book_no وقيداً فريداً رباعياً لتمكين ذلك، وأسقط
--    القيد الفريد القديم — لكنه بحث عن constraint_type = 'UNIQUE' وحده،
--    فنجا المفتاح الأساسي وظلّ يمنع الكتاب الثاني.
--
--    تحقّقت منه على PostgreSQL: إدراج الكتاب الثاني لنفس المادة يُرفض
--    بـ unique_violation. أي أن ميزة الكتب الثلاثة لا تعمل اليوم.
--
--    الإصلاح في supabase/fix_book_sources_pk.sql (يُنفَّذ بقرار منك).

create table if not exists public.book_sources (
  grade         text not null,
  subject       text not null,
  semester      text not null,
  base_path     text,
  page_count    integer,
  offset_pages  integer default 1,
  book_no       integer not null default 1,
  updated_at    timestamptz default now(),
  updated_by    text,
  primary key (grade, subject, semester)      -- ← هذا ما يمنع تعدّد الكتب
);

alter table public.book_sources
  drop constraint if exists book_sources_grade_subject_semester_book_no_key;
alter table public.book_sources
  add constraint book_sources_grade_subject_semester_book_no_key
  unique (grade, subject, semester, book_no);

alter table public.book_sources enable row level security;

-- ③ في الإنتاج زوجان متطابقان: هذان، ومعهما booksrc_read وbooksrc_admin_write
--    اللذان أنشأتُهما في النسخة التقديرية من هذا الملف قبل أن أستخرج البنية.
--    نُبقي الاسمين الأصليين هنا لأن هذا ملف توثيق لا ابتكار،
--    والمكرّران يُسقَطان في cleanup_duplicates.sql
drop policy if exists "read book_sources" on public.book_sources;
create policy "read book_sources" on public.book_sources
  for select to authenticated using (true);

drop policy if exists "admin write book_sources" on public.book_sources;
create policy "admin write book_sources" on public.book_sources
  for all to authenticated using (is_app_admin()) with check (is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٣) cycle1_profiles — ملف المعلمة  (٣ صفوف)
-- ─────────────────────────────────────────────────────────────
-- صف واحد لكل معلمة، وكل عملها داخل عمود data. أي كتابة عليه بحالة ناقصة
-- تمحو الباقي — راجع قسم «بيانات المعلمات» في loop-constraints.md.
--
-- بنية data (يفرضها الكود لا القاعدة):
--   display_name      اسمها
--   semester          الفصل الدراسي
--   setupDone         هل أكملت الإعداد
--   grades[]          الصفوف، وداخل كل صف classes[] بالشعب والمواد والطالبات
--   plan_units{}      وحدات ودروس كل (صف|مادة)
--   plan_state{}      حالة كل درس: أُنجز؟ خطة؟ ملخص؟ لعبة؟ ولأي شعبة؟
--   stars{}           نجوم كل طالبة لكل شعبة
--   beh_log{}         سجل السلوك بالتواريخ
--   timetable{}       الجدول الأسبوعي وأوقات الحصص
--   calendar_events{} أحداث التقويم
--   user_tasks[]      مهامها اليومية
--
-- ملحوظة: id ليس عليه مفتاح أجنبي إلى auth.users في الإنتاج — الربط
-- بالحساب يقع في الكود وحده. حذف حساب لا يحذف ملفه تلقائياً.

create table if not exists public.cycle1_profiles (
  id          uuid primary key,
  email       text,
  data        jsonb default '{}'::jsonb,
  updated_at  timestamptz default now()
);

alter table public.cycle1_profiles enable row level security;

-- ③ ثلاث سياسات حيث تكفي اثنتان: cycle1_own (كل معلمة تُدير ملفها)
--    وcycle1_admin_select (المشرف يقرأ). وc1prof_own تجمعهما فتُكرّرهما.
--    لا ثغرة — كلها تشترط auth.uid() = id أو is_app_admin() — لكن التكرار
--    يجعل مراجعة الصلاحيات لاحقاً أصعب مما ينبغي.
drop policy if exists cycle1_own on public.cycle1_profiles;
create policy cycle1_own on public.cycle1_profiles
  for all to authenticated
  using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists cycle1_admin_select on public.cycle1_profiles;
create policy cycle1_admin_select on public.cycle1_profiles
  for select to authenticated using (is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٤) allowed_emails — بوابة الدخول  (٥ صفوف)
-- ─────────────────────────────────────────────────────────────
-- غير المسجّل هنا لا يدخل ولو كان له حساب. وعمود cycle يفصل الحلقتين:
--   'main'   الصفوف ٥–١٢ (الموقع الرئيسي)
--   'cycle1' الصفوف ١–٤  (صفحة الحلقة الأولى)
--
-- ⚠️ العمود "user name" فيه مسافة داخل اسمه. يعمل، لكنه يُلزم بوضع علامتَي
--    اقتباس حوله في كل استعلام. لو أردتَ تسميته user_name يوماً فذلك تعديل
--    بسيط لكنه يمسّ كل ما يقرؤه.

create table if not exists public.allowed_emails (
  email       text primary key,
  cycle       text not null default 'main',
  added_at    timestamptz default now(),
  "user name" text
);

alter table public.allowed_emails enable row level security;

-- ③ ⚠️ سياستان متعارضتان في الأثر:
--      allowed_own_select  → المستخدم يقرأ بريده وحده (المقصود)
--      anyone_can_check    → using: true  ← تُبطل الأولى تماماً
--    والنتيجة أن أي معلمة مسجّلة تستطيع قراءة قائمة البُرد المصرّح لها
--    كاملة. ليست ثغرة خطيرة (بُرد لا كلمات مرور)، لكنها كشف غير مقصود.
--    الحذف في supabase/cleanup_duplicates.sql — وتحقّق أولاً أن شيئاً لا
--    يعتمد على القراءة المفتوحة قبل الدخول.
drop policy if exists allowed_own_select on public.allowed_emails;
create policy allowed_own_select on public.allowed_emails
  for select to authenticated
  using (lower(email) = lower(auth.jwt()->>'email') or is_app_admin());

drop policy if exists allowed_own_insert on public.allowed_emails;
create policy allowed_own_insert on public.allowed_emails
  for insert to authenticated
  with check (lower(email) = lower(auth.jwt()->>'email') or is_app_admin());

drop policy if exists allowed_admin_write on public.allowed_emails;
create policy allowed_admin_write on public.allowed_emails
  for all to authenticated
  using (is_app_admin()) with check (is_app_admin());
