-- ══════════════════════════════════════════════════════════════════════
-- الجداول الأساسية الأربعة — إعادة بناء
-- ══════════════════════════════════════════════════════════════════════
--
-- هذه الجداول أُنشئت يدوياً في لوحة Supabase قبل أن يبدأ حفظ الترحيلات في
-- المشروع، فلا ملف لها. وهي من أهم ما في النظام:
--   curriculum       المنهج كله — يُقرأ ٣٩ مرة في الكود
--   book_sources     صور صفحات الكتب
--   cycle1_profiles  ملفات المعلمات: صفوفهن وطالباتهن ونجومهن وخططهن
--   allowed_emails   بوابة الدخول
--
-- ⚠️ اقرأ هذا قبل تشغيل الملف على أي قاعدة
--
-- لم يُستخرج هذا من قاعدة البيانات مباشرةً — الشبكة تحجب supabase.co من
-- بيئة العمل. بُني من مصدرين:
--   ✅ مؤكَّد   — ملفات SQL موجودة في المشروع (مذكور مصدرها عند كل بند)
--   ~ مستنتَج  — من طريقة استعمال الكود للأعمدة
--
-- فالأسماء صحيحة، لكن بعض الأنواع والقيود والفهارس تقديرية. استعمله وثيقةً
-- مرجعية، ولا تُعِد به بناء قاعدة إنتاج قبل استبداله بالبنية الحقيقية.
--
-- لجعله مطابقاً: شغّل الاستعلام في introspect.sql على قاعدتك وسلّم مخرجاته،
-- فيُستبدل هذا الملف بالبنية الفعلية.
--
-- الملف آمن للتشغيل على قاعدة قائمة: كل شيء فيه `if not exists`
-- أو `add column if not exists`، فلا يُتلف بيانات ولا يُسقط جدولاً.
-- ══════════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;


-- ─────────────────────────────────────────────────────────────
-- ١) curriculum — المنهج: وحدات ودروس كل مادة
-- ─────────────────────────────────────────────────────────────
-- منه يُشتقّ رقم الدرس الموحّد (stableLessonId) الذي يربط المعلمات ببعضهن:
--   hash(semester | subject | grade | unit | lesson)
-- فأي تعديل على نصّ هذه الأعمدة يُغيّر الرقم ويقطع الربط بالمخزن المشترك.

create table if not exists public.curriculum (
  id        bigint generated by default as identity primary key,  -- ~ مستنتَج
  semester  text not null,      -- ~ «الفصل الأول» / «الفصل الثاني»
  grade     text not null,      -- ~ نصّ لا رقم: الكود يمرّره String(grade)
  subject   text not null,      -- ~
  unit      text not null,      -- ~ اسم الوحدة
  lesson    text not null,      -- ~ اسم الدرس
  sort      integer,            -- ~ ترتيب الدرس داخل المادة
  page      text,               -- ~ نصّ: الكود يقرؤه بـ parseInt
  book_no   integer not null default 1   -- ✅ 20260714_book_sources_multi_book.sql
);

-- الاستعلام الأكثر تكراراً في التطبيق كله
create index if not exists curriculum_lookup
  on public.curriculum (semester, subject, grade, sort);

alter table public.curriculum enable row level security;   -- ✅ supabase_security_migration.sql

-- ✅ منقولة حرفياً من supabase_security_migration.sql
drop policy if exists curr_read on public.curriculum;
create policy curr_read on public.curriculum
  for select to authenticated using (true);

drop policy if exists curr_admin_write on public.curriculum;
create policy curr_admin_write on public.curriculum
  for all to authenticated using (is_app_admin()) with check (is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٢) book_sources — أين تُخزَّن صور صفحات كل كتاب
-- ─────────────────────────────────────────────────────────────
-- offset_pages: الفرق بين رقم الصفحة المطبوع ورقم ملف الصورة.
-- الحلقة الأولى استثناء: للمادة الواحدة ثلاثة كتب في الفصل، ولذلك أُضيف book_no.

create table if not exists public.book_sources (
  id            bigint generated by default as identity primary key,  -- ~ مستنتَج
  grade         text not null,     -- ~
  subject       text not null,     -- ~
  semester      text not null,     -- ~
  base_path     text,              -- ~ مسار المجلد داخل مخزن library-files
  page_count    integer,           -- ~ عدد صفحات الكتاب
  offset_pages  integer default 1, -- ~ فرق الترقيم
  book_no       integer not null default 1   -- ✅ 20260714
);

-- ✅ منقول حرفياً من 20260714 (استبدل قيداً أقدم على ثلاثة أعمدة)
alter table public.book_sources
  drop constraint if exists book_sources_grade_subject_semester_book_no_key;
alter table public.book_sources
  add constraint book_sources_grade_subject_semester_book_no_key
  unique (grade, subject, semester, book_no);

alter table public.book_sources enable row level security;   -- ~ مستنتَج

drop policy if exists booksrc_read on public.book_sources;
create policy booksrc_read on public.book_sources
  for select to authenticated using (true);

drop policy if exists booksrc_admin_write on public.book_sources;
create policy booksrc_admin_write on public.book_sources
  for all to authenticated using (is_app_admin()) with check (is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٣) cycle1_profiles — ملف المعلمة (أخطر جدول في النظام)
-- ─────────────────────────────────────────────────────────────
-- صف واحد لكل معلمة، وكل عملها داخل عمود data. أي كتابة عليه بحالة ناقصة
-- تمحو الباقي — راجع قسم «بيانات المعلمات» في loop-constraints.md.
--
-- بنية data (من الكود، وليست مفروضة في القاعدة):
--   display_name     اسمها
--   semester         الفصل الدراسي
--   setupDone        هل أكملت الإعداد
--   grades[]         الصفوف، وداخل كل صف classes[] بالشعب والمواد والطالبات
--   plan_units{}     وحدات ودروس كل (صف|مادة)
--   plan_state{}     حالة كل درس: أُنجز؟ خطة؟ ملخص؟ لعبة؟ ولأي شعبة؟
--   stars{}          نجوم كل طالبة لكل شعبة
--   beh_log{}        سجل السلوك بالتواريخ
--   timetable{}      الجدول الأسبوعي وأوقات الحصص
--   calendar_events{} أحداث التقويم
--   user_tasks[]     مهامها اليومية

create table if not exists public.cycle1_profiles (
  id          uuid primary key references auth.users(id) on delete cascade,  -- ~
  email       text,                                    -- ~
  data        jsonb not null default '{}'::jsonb,      -- ~
  updated_at  timestamptz default now()                -- ~
);

alter table public.cycle1_profiles enable row level security;   -- ~ مستنتَج

-- ~ مستنتَجة: كل معلمة تقرأ وتكتب ملفها وحدها، والمشرف يرى الكل
--   (يعتمد على أن manager.html يقرأ id,email,data لكل المعلمات)
drop policy if exists c1prof_own on public.cycle1_profiles;
create policy c1prof_own on public.cycle1_profiles
  for all to authenticated
  using (id = auth.uid() or is_app_admin())
  with check (id = auth.uid() or is_app_admin());


-- ─────────────────────────────────────────────────────────────
-- ٤) allowed_emails — بوابة الدخول
-- ─────────────────────────────────────────────────────────────
-- غير المسجّل هنا لا يدخل ولو كان له حساب. وعمود cycle يفصل الحلقتين:
--   'main'   الصفوف ٥–١٢ (الموقع الرئيسي)
--   'cycle1' الصفوف ١–٤  (صفحة الحلقة الأولى)

create table if not exists public.allowed_emails (
  email  text primary key,                       -- ~ مستنتَج
  cycle  text not null default 'main'            -- ✅ supabase_allowed_emails_cycle_migration.sql
);

alter table public.allowed_emails enable row level security;   -- ✅ supabase_security_migration.sql

-- ✅ الثلاث منقولة حرفياً من supabase_security_migration.sql
drop policy if exists allowed_own_select on public.allowed_emails;
create policy allowed_own_select on public.allowed_emails
  for select to authenticated
  using (lower(email) = lower(auth.jwt()->>'email') or is_app_admin());

drop policy if exists allowed_own_insert on public.allowed_emails;
create policy allowed_own_insert on public.allowed_emails
  for insert to authenticated
  with check (lower(email) = lower(auth.jwt()->>'email') or is_app_admin());

drop policy if exists allowed_admin_write on public.allowed_emails;
create policy allowed_admin_write on public.allowed_emails
  for all to authenticated
  using (is_app_admin()) with check (is_app_admin());
