-- ميزة «تحاضير الحلقة الأولى»: توليد تحاضير بمطابقة دليل المعلم مع فهرس
-- الكتاب الموجود مسبقاً في curriculum، ثم توليد تحضير كل درس من صفحاته في
-- الكتاب + دليل المعلم، بتنسيق قالبٍ معتمد. مشرف فقط في كل مكان (نفس نمط
-- book_sources/curriculum: قراءة لكل المعلمات إن احتجنا لاحقاً، كتابة للمشرف حصراً).

-- ─────────────────────────────────────────────────────────────
-- ١) teacher_guides — دليل المعلم المرفوع لكل (فصل × صف × مادة)
-- ─────────────────────────────────────────────────────────────
create table if not exists public.teacher_guides (
  id            bigint generated by default as identity primary key,
  semester      text not null,
  grade         integer not null,
  subject       text not null,
  base_path     text,                 -- مسار صور الصفحات في library-files (مثل book_sources.base_path)
  page_count    integer,
  offset_pages  integer default 1,
  status        text not null default 'uploaded',  -- uploaded | indexing | indexed | index_failed
  toc           jsonb,                -- [{unit,lesson,page,matched_lesson_id,match_confidence}]
  indexed_at    timestamptz,
  created_by    uuid references auth.users(id) on delete set null,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  unique (grade, subject, semester)
);

alter table public.teacher_guides enable row level security;

drop policy if exists "teacher_guides_admin_all" on public.teacher_guides;
create policy "teacher_guides_admin_all" on public.teacher_guides
  for all to authenticated using (is_app_admin()) with check (is_app_admin());

-- ─────────────────────────────────────────────────────────────
-- ٢) lesson_prep_generations — التحضير المولَّد لكل درس (مسودة/معتمد)
-- ─────────────────────────────────────────────────────────────
create table if not exists public.lesson_prep_generations (
  id               bigint generated by default as identity primary key,
  curriculum_id    bigint references public.curriculum(id) on delete cascade,
  teacher_guide_id bigint references public.teacher_guides(id) on delete set null,
  semester         text not null,
  grade            integer not null,
  subject          text not null,
  unit             text not null,
  lesson           text not null,
  content          jsonb not null,      -- محتوى التحضير المُولَّد بحسب هيكل القالب
  status           text not null default 'draft',   -- draft | approved
  model            text,
  created_by       uuid references auth.users(id) on delete set null,
  created_at       timestamptz default now(),
  approved_at      timestamptz,
  unique (curriculum_id)
);

alter table public.lesson_prep_generations enable row level security;

drop policy if exists "lesson_prep_generations_admin_all" on public.lesson_prep_generations;
create policy "lesson_prep_generations_admin_all" on public.lesson_prep_generations
  for all to authenticated using (is_app_admin()) with check (is_app_admin());

-- ─────────────────────────────────────────────────────────────
-- ٣) فهرس بحثٍ سريع لتحاضير مادةٍ/صفٍ/فصلٍ بعينه (شاشة الإدارة تُحمّل دفعة واحدة)
-- ─────────────────────────────────────────────────────────────
create index if not exists idx_lesson_prep_generations_scope
  on public.lesson_prep_generations (semester, grade, subject);

create index if not exists idx_teacher_guides_scope
  on public.teacher_guides (semester, grade, subject);

-- تحقّق: select * from teacher_guides; select * from lesson_prep_generations; -- كلاهما فارغ بعد هذه الهجرة
